# Generated by Django 4.2.1 on 2023-06-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
