# Generated by Django 4.2.1 on 2023-06-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='provider',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
