# Generated by Django 4.2.1 on 2023-06-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_remove_purchase_product_purchase_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='product',
            new_name='products',
        ),
        migrations.AddField(
            model_name='purchase',
            name='order_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
