# Generated by Django 4.2.1 on 2023-06-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='products',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='stripe_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
