# Generated by Django 4.2.1 on 2023-06-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_merge_20230622_1716'),
        ('purchases', '0003_purchase_kakaopay_checkout_tid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
