# Generated by Django 4.2.1 on 2023-06-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stripe_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stripe_product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
