# Generated by Django 4.2.1 on 2023-06-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
        ('products', '0002_remove_product_stripe_price_and_more'),
    ]

    operations = [
    ]
