# Generated by Django 4.2.1 on 2023-06-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name_alter_product_updated'),
        ('products', '0002_product_stripe_price_product_stripe_price_id_and_more'),
    ]

    operations = [
    ]
