# Generated by Django 4.2.1 on 2023-06-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_name_alter_product_updated"),
        ("products", "0003_product_image"),
    ]

    operations = []
