# Generated by Django 4.2.1 on 2023-06-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_20230619_1730'),
        ('products', '0003_product_image'),
    ]

    operations = [
    ]
