# Generated by Django 4.2.1 on 2023-06-21 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
        ('products', '0004_product_stock'),
    ]

    operations = [
    ]
