# Generated by Django 4.2.1 on 2023-06-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_0003_merge_20230619_1730_0003_product_image'),
        ('products', '0005_merge_0003_product_image_0004_product_stock'),
    ]

    operations = [
    ]
