# Generated by Django 4.2.1 on 2023-06-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_20230621_1100'),
        ('products', '0006_merge_20230621_1754'),
    ]

    operations = [
    ]
